%=======================================================================================================
% TEMPLATE OF THE STRUCT DATI
%=======================================================================================================

function [Dati]=C_dati(test)

if (strcmp(test,'Test1'))
    Dati = struct( 'name',             test,...
               ... % Test name
               'domain',           [0,3],...                          
               ... % Domain bounds   
               'bc',              'R', ...
               ... % D = Dirichlet, N = Neumann, R = Robin, 
               ... % P = Periodic, A = Absorbing 
               'c2',               1, ...
               ... % Diffusive term ...
               'T',               0.5, ...
               ... % Final time ...
               'dt',            0.01, ...
               ... % Time step
               'u0',      '0.*x', ...
               ... % Initial condition u               
               'v0',      '2*pi*sin(2*pi*x)', ...
               ... % Initial condition  du/dt        
               'exact_sol',       'sin(2*pi*x).*sin(2*pi*t)',...      
               ... % Definition of exact solution or lifting function Rg
               'grad_exact',     '2*pi*cos(2*pi*x).*sin(2*pi*t)',...    
               ... % du/dx 
               'force',           '0.*x.*t',...  
               ... % Forcing term
               'neumann1',        '2*pi*sin(2*pi*t)',...
               ... % -c2du/dx(0,t) = g1(t)
               'neumann2',        '2*pi*sin(2*pi*t)',...
               ... %  c2du/dx(L,t) = g2(t)               
               'fem',              'P1',...         
               ... % P1-fe
               'nqn_1D',            2,...           
               ... % Number of quad. points per element
               'MeshType',         'TS', ...        
               ... % uniform regular mesh
               'refinement_vector', [4,5,6,7],...   
               ... % Refinement levels for  the error analysis
               'visual_graph',      'Y',...
               ... % Visualization of the solution
               'plot_errors',       'Y', ...
               ...% Compute Errors 
               'timeIntScheme',    'LF' ...
               ... % Time Integration scheme
               );

elseif (strcmp(test,'Test2'))
    Dati = struct( 'name',             test,...
               ... % Test name
               'domain',           [-1,1],...                          
               ... % Domain bounds   
               'bc',              'P', ...
               ... % D = Dirichlet, N = Neumann, R = Robin, 
               ... % P = Periodic, A = Absorbing 
               'c2',               10^2/4^2, ...
               ... % Diffusive term ...
               'T',               1, ...
               ... % Final time ...
               'dt',            0.01, ...
               ... % Time step
               'u0',      'cos(4*pi*x)', ...
               ... % Initial condition u               
               'v0',      '10*pi*sin(4*pi*x)', ...
               ... % Initial condition  du/dt        
               'exact_sol',       'cos(4*pi*x-10*pi*t)',...      
               ... % Definition of exact solution or lifting function Rg
               'grad_exact',     '-4*pi*sin(4*pi*x-10*pi*t)',...    
               ... % du/dx 
               'force',           '0.*x.*t',...  
               ... % Forcing term
               'neumann1',        '0.*x.*t',...
               ... % -c2du/dx(0,t) = g1(t)
               'neumann2',        '0.*x.*t',...
               ... %  c2du/dx(L,t) = g2(t)               
               'fem',              'P1',...         
               ... % P1-fe
               'nqn_1D',            2,...           
               ... % Number of quad. points per element
               'MeshType',         'TS', ...        
               ... % uniform regular mesh
               'refinement_vector', [4,5,6,7],...   
               ... % Refinement levels for  the error analysis
               'visual_graph',      'Y',...
               ... % Visualization of the solution
               'plot_errors',       'Y', ...
               ...% Compute Errors 
               'timeIntScheme',    'LF' ...
               ... % Time Integration scheme
               );

elseif (strcmp(test,'Test3'))
    Dati = struct( 'name',             test,...
               ... % Test name
               'domain',           [-5,5],...                          
               ... % Domain bounds   
               'bc',              'A', ...
               ... % D = Dirichlet, N = Neumann, R = Robin, 
               ... % P = Periodic, A = Absorbing 
               'c2',               2, ...
               ... % Diffusive term ...
               'T',               5, ...
               ... % Final time ...
               'dt',            0.01, ...
               ... % Time step
               'u0',      'exp(-x.^2)', ...
               ... % Initial condition u               
               'v0',      '0*x', ...
               ... % Initial condition  du/dt        
               'exact_sol',       '0.*x.*t',...      
               ... % Definition of exact solution or lifting function Rg
               'grad_exact',     '0.*x.*t',...    
               ... % du/dx 
               'force',           '0.*x.*t',...  
               ... % Forcing term
               'neumann1',        '0.*x.*t',...
               ... % -c2du/dx(0,t) = g1(t)
               'neumann2',        '0.*x.*t',...
               ... %  c2du/dx(L,t) = g2(t)               
               'fem',              'P1',...         
               ... % P1-fe
               'nqn_1D',            2,...           
               ... % Number of quad. points per element
               'MeshType',         'TS', ...        
               ... % uniform regular mesh
               'refinement_vector', [4,5,6,7],...   
               ... % Refinement levels for  the error analysis
               'visual_graph',      'Y',...
               ... % Visualization of the solution
               'plot_errors',       'Y', ...
               ...% Compute Errors 
               'timeIntScheme',    'LF' ...
               ... % Time Integration scheme
               );           
elseif (strcmp(test,'TestHW1E3S0'))
    Dati = struct( 'name',             test,...
               ... % Test name
               'domain',           [0,1],...                          
               ... % Domain bounds   
               'bc',              'D', ...
               ... % D = Dirichlet, N = Neumann, R = Robin, 
               ... % P = Periodic, A = Absorbing, M = Mixed
               'c2',               1, ...
               ... % Diffusive term ...
               'T',               1, ...
               ... % Final time ...
               'dt',            0.001, ...
               ... % Time step
               'u0',      '0*x', ...
               ... % Initial condition u               
               'v0',      '2*pi*cos(2*pi*x)', ...
               ... % Initial condition  du/dt        
               'exact_sol',       'cos(2*pi*x).*sin(2*pi*t)',...      
               ... % Definition of exact solution or lifting function Rg
               'grad_exact',     '-2*pi*sin(2*pi*x).*sin(2*pi*t)',...    
               ... % du/dx 
               'force',           '0.*x.*t',...  
               ... % Forcing term
               'neumann1',        '0.*x.*t',...
               ... % -c2du/dx(0,t) = g1(t)
               'neumann2',        '0.*x.*t',...
               ... %  c2du/dx(L,t) = g2(t)               
               'fem',              'P1',...         
               ... % P1-fe
               'nqn_1D',            2,...           
               ... % Number of quad. points per element
               'MeshType',         'TS', ...        
               ... % uniform regular mesh
               'refinement_vector', [4,5,6,7],...   
               ... % Refinement levels for  the error analysis
               'visual_graph',      'Y',...
               ... % Visualization of the solution
               'plot_errors',       'Y', ...
               ...% Compute Errors 
               'Lifting1',          'cos(2*pi*t)', ...
               ...%Lifting Function left side
               'Lifting1tt',          '-4*pi^2*cos(2*pi*t)', ...
               ...%Lifting Function left side
               'timeIntScheme',    'NLF', ...
               ... % Time Integration scheme
               'shape',                '0*x+1' ...
               ... % Shape of tube 
               );
elseif (strcmp(test,'TestHW1E3S1'))
    Dati = struct( 'name',             test,...
               ... % Test name
               'domain',           [0,1],...                          
               ... % Domain bounds   
               'bc',              'M', ...
               ... % D = Dirichlet, N = Neumann, R = Robin, 
               ... % P = Periodic, A = Absorbing, M = Mixed, F= Forced
               'c2',               1, ...
               ... % Diffusive term ...
               'T',               1, ...
               ... % Final time ...
               'dt',            0.01, ...
               ... % Time step
               'u0',      '0*x', ...
               ... % Initial condition u               
               'v0',      '2*pi*cos(2*pi*x)', ...
               ... % Initial condition  du/dt        
               'exact_sol',       'cos(2*pi*x).*sin(2*pi*t)',...      
               ... % Definition of exact solution or lifting function Rg
               'grad_exact',     '-2*pi*sin(2*pi*x).*sin(2*pi*t)',...    
               ... % du/dx 
               'force',           '(2*pi)*(8*x+4).*(sin(2*pi*x).*sin(2*pi*t))',...  
               ... % Forcing term
               'neumann1',        '0.*x.*t',...
               ... % -c2du/dx(0,t) = g1(t)
               'neumann2',        '0.*x.*t',...
               ... %  c2du/dx(L,t) = g2(t)               
               'fem',              'P1',...         
               ... % P1-fe
               'nqn_1D',            2,...           
               ... % Number of quad. points per element
               'MeshType',         'TS', ...        
               ... % uniform regular mesh
               'refinement_vector', [4,5,6,7],...   
               ... % Refinement levels for  the error analysis
               'visual_graph',      'Y',...
               ... % Visualization of the solution
               'plot_errors',       'Y', ...
               ...% Compute Errors 
               'Lifting1',          'cos(2*pi*t)', ...
               ...%Lifting Function left side
               'Lifting1tt',          '-4*pi^2*cos(2*pi*t)', ...
               ...%Lifting Function left side
               'timeIntScheme',    'NLF', ...
               ... % Time Integration scheme
               'shape',                '(1+2*x).^2' ...
               ... % Shape of tube 
               );
elseif (strcmp(test,'TestHW1E3S2'))
    Dati = struct( 'name',             test,...
               ... % Test name
               'domain',           [0,1],...                          
               ... % Domain bounds   
               'bc',              'M', ...
               ... % D = Dirichlet, N = Neumann, R = Robin, 
               ... % P = Periodic, A = Absorbing, M = Mixed
               'c2',               1, ...
               ... % Diffusive term ...
               'T',               1, ...
               ... % Final time ...
               'dt',            0.01, ...
               ... % Time step
               'u0',      '0*x', ...
               ... % Initial condition u               
               'v0',      '2*pi*cos(2*pi*x)', ...
               ... % Initial condition  du/dt        
               'exact_sol',       'cos(2*pi*x).*sin(2*pi*t)',...      
               ... % Definition of exact solution or lifting function Rg
               'grad_exact',     '-2*pi*sin(2*pi*x).*sin(2*pi*t)',...    
               ... % du/dx 
               'force',           '-(30*(pi^2)/4)*cos(5*pi*x).*sin(2*pi*x).*sin(2*pi*t)',...  
               ... % Forcing term
               'neumann1',        '0.*x.*t',...
               ... % -c2du/dx(0,t) = g1(t)
               'neumann2',        '0.*x.*t',...
               ... %  c2du/dx(L,t) = g2(t)               
               'fem',              'P1',...         
               ... % P1-fe
               'nqn_1D',            2,...           
               ... % Number of quad. points per element
               'MeshType',         'TS', ...        
               ... % uniform regular mesh
               'refinement_vector', [4,5,6,7],...   
               ... % Refinement levels for  the error analysis
               'visual_graph',      'Y',...
               ... % Visualization of the solution
               'plot_errors',       'Y', ...
               ...% Compute Errors
               'timeIntScheme',    'NLF', ...
               ... % Time Integration scheme
               'shape',                '1-(3/4)*sin(5*pi*x)' ...
               ... % Shape of tube 
               );
    elseif (strcmp(test,'TestHW1E4S0'))
    Dati = struct( 'name',             test,...
               ... % Test name
               'domain',           [0,1],...                          
               ... % Domain bounds   
               'bc',              'F', ...
               ... % D = Dirichlet, N = Neumann, R = Robin, 
               ... % P = Periodic, A = Absorbing, M = Mixed, F = Forced
               'c2',               4, ...
               ... % Diffusive term ...
               'T',               1, ...
               ... % Final time ...
               'dt',            0.0001, ...
               ... % Time step
               'u0',      '0*x', ...
               ... % Initial condition u               
               'v0',      '0*x', ...
               ... % Initial condition  du/dt        
               'exact_sol',       'cos(2*pi*x).*sin(2*pi*t)',...      
               ... % Definition of exact solution or lifting function Rg
               'grad_exact',     '-2*pi*sin(2*pi*x).*sin(2*pi*t)',...    
               ... % du/dx 
               'force',           '0.*x.*t',...  
               ... % Forcing term
               'neumann1',        '0.*x.*t',...
               ... % -c2du/dx(0,t) = g1(t)
               'neumann2',        '0.*x.*t',...
               ... %  c2du/dx(L,t) = g2(t)               
               'fem',              'P1',...         
               ... % P1-fe
               'nqn_1D',            2,...           
               ... % Number of quad. points per element
               'MeshType',         'TS', ...        
               ... % uniform regular mesh
               'refinement_vector', [4,5,6,7],...   
               ... % Refinement levels for  the error analysis
               'visual_graph',      'Y',...
               ... % Visualization of the solution
               'plot_errors',       'Y', ...
               ...% Compute Errors
               'timeIntScheme',    'NLF', ...
               ... % Time Integration scheme
               'shape',                '0*x+1', ...
               ... % Shape of tube 
                'g',                    'u_gg = 0; if (abs(t-0.2) <= 0.1) u_gg = 0.5 *(1+cos(pi*(t-0.2)/0.1));  end',...
               ... % function 
               "st_plot",               'Y'...
               ... %print space time plot
               );
    elseif (strcmp(test,'TestHW1E4S1'))
    Dati = struct( 'name',             test,...
               ... % Test name
               'domain',           [0,1],...                          
               ... % Domain bounds   
               'bc',              'F', ...
               ... % D = Dirichlet, N = Neumann, R = Robin, 
               ... % P = Periodic, A = Absorbing, M = Mixed, F = Forced
               'c2',               4, ...
               ... % Diffusive term ...
               'T',               1, ...
               ... % Final time ...
               'dt',            0.0001, ...
               ... % Time step
               'u0',      '0*x', ...
               ... % Initial condition u               
               'v0',      '0*x', ...
               ... % Initial condition  du/dt        
               'exact_sol',       'cos(2*pi*x).*sin(2*pi*t)',...      
               ... % Definition of exact solution or lifting function Rg
               'grad_exact',     '-2*pi*sin(2*pi*x).*sin(2*pi*t)',...    
               ... % du/dx 
               'force',           '0.*x.*t',...  
               ... % Forcing term
               'neumann1',        '0.*x.*t',...
               ... % -c2du/dx(0,t) = g1(t)
               'neumann2',        '0.*x.*t',...
               ... %  c2du/dx(L,t) = g2(t)               
               'fem',              'P1',...         
               ... % P1-fe
               'nqn_1D',            2,...           
               ... % Number of quad. points per element
               'MeshType',         'TS', ...        
               ... % uniform regular mesh
               'refinement_vector', [4,5,6,7],...   
               ... % Refinement levels for  the error analysis
               'visual_graph',      'Y',...
               ... % Visualization of the solution
               'plot_errors',       'Y', ...
               ...% Compute Errors
               'timeIntScheme',    'NLF', ...
               ... % Time Integration scheme
               'shape',                '(1+2*x).^2', ...
               ... % Shape of tube 
                'g',                    'u_gg = 0; if (abs(t-0.2) <= 0.1) u_gg = 0.5 *(1+cos(pi*(t-0.2)/0.1));  end',...
               ... % function 
               "st_plot",               'Y'...
               ... %print space time plot
               );
    elseif (strcmp(test,'TestHW1E4S2'))
    Dati = struct( 'name',             test,...
               ... % Test name
               'domain',           [0,1],...                          
               ... % Domain bounds   
               'bc',              'F', ...
               ... % D = Dirichlet, N = Neumann, R = Robin, 
               ... % P = Periodic, A = Absorbing, M = Mixed, F = Forced
               'c2',               4, ...
               ... % Diffusive term ...
               'T',               1, ...
               ... % Final time ...
               'dt',            0.01, ...
               ... % Time step
               'u0',      '0*x', ...
               ... % Initial condition u               
               'v0',      '0*x', ...
               ... % Initial condition  du/dt        
               'exact_sol',       'cos(2*pi*x).*sin(2*pi*t)',...      
               ... % Definition of exact solution or lifting function Rg
               'grad_exact',     '-2*pi*sin(2*pi*x).*sin(2*pi*t)',...    
               ... % du/dx 
               'force',           '0.*x.*t',...  
               ... % Forcing term
               'neumann1',        '0.*x.*t',...
               ... % -c2du/dx(0,t) = g1(t)
               'neumann2',        '0.*x.*t',...
               ... %  c2du/dx(L,t) = g2(t)               
               'fem',              'P1',...         
               ... % P1-fe
               'nqn_1D',            2,...           
               ... % Number of quad. points per element
               'MeshType',         'TS', ...        
               ... % uniform regular mesh
               'refinement_vector', [4,5,6,7],...   
               ... % Refinement levels for  the error analysis
               'visual_graph',      'Y',...
               ... % Visualization of the solution
               'plot_errors',       'Y', ...
               ...% Compute Errors
               'timeIntScheme',    'NLF', ...
               ... % Time Integration scheme
               'shape',                '1-(3/4)*sin(5*pi*x)', ...
               ... % Shape of tube 
                'g',                    'u_gg = 0; if (abs(t-0.2) <= 0.1) u_gg = 0.5 *(1+cos(pi*(t-0.2)/0.1));  end',...
               ... % function 
               "st_plot",               'Y'...
               ... %print space time plot
               );
end



